spring.application.name=order-service
server.port=8080

outbox.poll-rate-ms=${OUTBOX_POLL_RATE_MS:1000}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5449/orders}
spring.datasource.username=${DB_USERNAME:app}
spring.datasource.password=${DB_PASSWORD:app}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=true

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

spring.rabbitmq.template.observation-enabled=true

management.endpoints.web.exposure.include=health,info,metrics
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=${OTLP_TRACING_ENDPOINT:http://localhost:18890/v1/traces}
