server.port=8080

spring.application.name=order-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5449/orders}
spring.datasource.username=${DB_USERNAME:app}
spring.datasource.password=${DB_PASSWORD:app}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=true

otel.exporter.otlp.endpoint=http://localhost:18889
otel.exporter.otlp.protocol=grpc

# These default to otlp already; explicit for clarity
otel.traces.exporter=otlp
otel.metrics.exporter=otlp
otel.logs.exporter=otlp