server.port=8081

spring.application.name=notification-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5449/notifications}
spring.datasource.username=${DB_USERNAME:app}
spring.datasource.password=${DB_PASSWORD:app}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=true