server.port=8080

spring.application.name=order-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5449/orders}
spring.datasource.username=${DB_USERNAME:app}
spring.datasource.password=${DB_PASSWORD:app}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=true